name: lab7

services:
  lab7:
    build:
      context: .
      dockerfile: Dockerfile.lab7
    image: lab7-pyspark:latest
    container_name: lab7-pyspark
    working_dir: /opt/app/lab7
    volumes:
      - ./:/opt/app/lab7
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      LAB7_SPARK_MASTER: "local[2]"
      LAB7_DRIVER_MEMORY: "1g"
      PYTHONUNBUFFERED: "1"
